style: ""
template: CHANGELOG.tpl.md
info:
  title: Changelog
  repository_url: https://github.com/w3c/respec
options:
  commits:
    filters:
      Type:
        - BREAKING
        - BREAKING CHANGE
        - feat
        - fix
        - hot fix
        - HOT FIX
        - perf
        - refactor
        - chore
        # - test
        # - tests
  commit_groups:
    sort_by: Custom
    title_order:
      - BREAKING
      - BREAKING CHANGE
      - feat
      - fix
      - HOT FIX
      - perf
      - refactor
      - chore
    title_maps:
      feat: Features and Enhancements
      fix: Bug Fixes
      HOT FIX: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Chores
      BREAKING CHANGE: BREAKING CHANGES
      BREAKING: BREAKING CHANGES
  header:
    pattern: "^([\\w ]+)(?:\\(([\\w\\$\\.\\-\\*\\s/]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
